### ISSUE TITLE
Can u help me?

### ISSUE THREAD

**Issue by Raxana7** [NeverW8/TwitchViewbot#1]

**Comment by Raxana7** [comment]
![image](https://user-images.githubusercontent.com/48220802/88461932-98b84300-ceb0-11ea-854d-1ee3904e4e64.png)

**Comment by NeverW8** [comment]
Hi Raxana, I don't know if you're trying to compile this or something, but if you want some help getting this up and running, please provide some more information.

Like, what command you did before this and how far along you've gotten into setting this up.

/Sheik
