### ISSUE TITLE
pip install jsonlib-python3

### ISSUE THREAD

**Issue by 1881pac** [NeverW8/TwitchViewbot#2]
It just gives error. And when i started .py file it says An error has occurred while trying to read arguments. Did you specify the channel?

**Comment by NeverW8** [comment]
Well, did you specify the channel?

**Comment by 1881pac** [comment]
I did. In code and while starting

**Comment by NeverW8** [comment]
Download the latest version of the script, update streamlink and replace the dev key with one of your own from https://dev.twitch.tv/
